[package]
name = "yarns"
version = "0.1.0"
authors = ["astory <astory11@yahoo.com>"]
description = "Simple lib for working with strings"
license = "MIT"
repository = "https://github.com/AlexStory/yarns"
keywords = ["string", "yarns"]
readme = "./README.md"

[dependencies]
